# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 16:02
from __future__ import unicode_literals

from django.db import migrations
import events.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170807_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=events.models.Event.path_and_rename, validators=[events.models.Event.file_size]),
        ),
    ]
