# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 12:13
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170808_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
        ),
    ]
