# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Bucharest', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='loc_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='maps',
            field=location_field.models.plain.PlainLocationField(default='None', max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='test',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
