# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20170814_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='test',
            new_name='title',
        ),
    ]
