# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20170814_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
    ]
