# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_location_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc_date',
            new_name='l_date',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='title',
            new_name='l_title',
        ),
    ]
