# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20170816_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='location',
            name='l_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Place'),
        ),
    ]
