# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 16:22
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20170818_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='l_title'),
        ),
    ]
