# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_location_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
    ]
