# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_location_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_field', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_title', models.CharField(max_length=256, verbose_name='Title')),
                ('o_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='l_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time'),
        ),
        migrations.AddField(
            model_name='optionfield',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Options'),
        ),
    ]
