# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 15:32
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0020_auto_20170910_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormElementEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_data', models.TextField(blank=True, null=True, verbose_name='Plugin data')),
                ('plugin_uid', models.CharField(max_length=255, verbose_name='Plugin name')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Position')),
            ],
            options={
                'verbose_name_plural': 'Form element entries',
                'verbose_name': 'Form element entry',
                'abstract': False,
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FormEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title', models.CharField(blank=True, help_text='Shown in templates if available.', max_length=255, null=True, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('is_public', models.BooleanField(default=False, help_text='Makes your form visible to the public.', verbose_name='Public?')),
                ('success_page_title', models.CharField(blank=True, help_text='Custom message title to display after valid form is submitted', max_length=255, null=True, verbose_name='Success page title')),
                ('success_page_message', models.TextField(blank=True, help_text='Custom message text to display after valid form is submitted', null=True, verbose_name='Success page body')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Form entries',
                'verbose_name': 'Form entry',
            },
        ),
        migrations.CreateModel(
            name='FormFieldsetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_repeatable', models.BooleanField(default=False, help_text='Makes your form fieldset repeatable.', verbose_name='Is repeatable?')),
                ('form_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.FormEntry', verbose_name='Form')),
            ],
            options={
                'verbose_name_plural': 'Form fieldset entries',
                'verbose_name': 'Form fieldset entry',
            },
        ),
        migrations.CreateModel(
            name='FormHandlerEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_data', models.TextField(blank=True, null=True, verbose_name='Plugin data')),
                ('plugin_uid', models.CharField(max_length=255, verbose_name='Plugin name')),
                ('form_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.FormEntry', verbose_name='Form')),
            ],
            options={
                'verbose_name_plural': 'Form handler entries',
                'verbose_name': 'Form handler entry',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='formelemententry',
            name='form_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.FormEntry', verbose_name='Form'),
        ),
        migrations.AddField(
            model_name='formelemententry',
            name='form_fieldset_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.FormFieldsetEntry', verbose_name='Form fieldset'),
        ),
        migrations.AlterUniqueTogether(
            name='formfieldsetentry',
            unique_together=set([('form_entry', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='formentry',
            unique_together=set([('user', 'slug'), ('user', 'name')]),
        ),
    ]
