# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_formelement_formhandler'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
