# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='List Title'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(default='Bucharest', max_length=255, verbose_name='Location Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='l_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Location Title'),
        ),
    ]
