# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_auto_20171001_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formhandlerentry',
            name='plugin_uid',
            field=models.CharField(default='db_store', max_length=255, verbose_name='Plugin name'),
        ),
    ]
