# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20171001_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formhandler',
            name='plugin_uid',
            field=models.CharField(default='db_store', editable=False, max_length=255, unique=True, verbose_name='Plugin UID'),
        ),
    ]
