# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20171002_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldsetentry',
            name='form_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.FormEntry', verbose_name='Form'),
        ),
    ]
