# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20171002_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelemententry',
            name='form_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.FormEntry', verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='formhandlerentry',
            name='form_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.FormEntry', verbose_name='Form'),
        ),
    ]
