# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20171003_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='First Name and Last Name')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('secret', models.CharField(blank=True, max_length=15, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
