# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_emailapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailapp',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterUniqueTogether(
            name='emailapp',
            unique_together=set([('event', 'email')]),
        ),
    ]
