# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20171007_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailapp',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
