# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0034_auto_20171008_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionfield',
            name='option',
        ),
        migrations.RemoveField(
            model_name='options',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('title', 'user')]),
        ),
        migrations.DeleteModel(
            name='OptionField',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
