# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20171019_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_quota',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('event', 'location_quota')]),
        ),
    ]
