# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0036_auto_20171019_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_quota',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('title', 'user'), ('title', 'location_quota')]),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_quota',
        ),
    ]
