# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0023_formelement_formhandler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFormDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data_headers', models.TextField(blank=True, null=True, verbose_name='Form data headers')),
                ('saved_data', models.TextField(blank=True, null=True, verbose_name='Plugin data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('form_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.FormEntry', verbose_name='Form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved form data entry',
                'verbose_name_plural': 'Saved form data entries',
                'db_table': 'db_store_savedformdataentry',
                'abstract': False,
            },
        ),
    ]
