# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedformdataentry',
            name='form_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Form'),
        ),
    ]
