# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event_value',
            field=models.IntegerField(default=1),
        ),
    ]
