# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171017_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emails_value',
            new_name='email_value',
        ),
    ]
